services:
  - type: web
    name: festlmacher-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Load from environment
      - key: JWT_SECRET
        sync: false # Load from environment  
      - key: FRONTEND_URL
        value: https://festlmacher.netlify.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    autoDeploy: true