services:
  - type: web
    name: festlmacher-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gey14853:Muhammed5858@festelmacher.egk1s.mongodb.net/festelmacher?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: festlmacher2024secure
      - key: FRONTEND_URL
        value: https://festlmacher.netlify.app
    autoDeploy: true